set number
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
set mouse=a 
set clipboard=unnamedplus
set numberwidth=1
syntax enable
set showcmd  
set ruler
set cursorline
set encoding=utf-8
set showmatch
set sw=2
set relativenumber
set laststatus=2
set bs=indent,eol,start
set relativenumber
set smarttab
set tabstop=2     
set shiftwidth=2
set expandtab
set hidden
set updatetime=50
set shortmess+=c
set splitright
set splitbelow

so ./plugins.vim
so ./plugins-config.vim
so ./maps.vim
